# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /share/apps/spack/envs/fgci-centos7-haswell/software/cmake/3.20.1/2yva6ru/bin/cmake

# The command to remove a file.
RM = /share/apps/spack/envs/fgci-centos7-haswell/software/cmake/3.20.1/2yva6ru/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /scratch/work/toppg1/TBG/TBG_LMC

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /scratch/work/toppg1/TBG/TBG_LMC

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/share/apps/spack/envs/fgci-centos7-haswell/software/cmake/3.20.1/2yva6ru/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/share/apps/spack/envs/fgci-centos7-haswell/software/cmake/3.20.1/2yva6ru/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /scratch/work/toppg1/TBG/TBG_LMC/CMakeFiles /scratch/work/toppg1/TBG/TBG_LMC//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /scratch/work/toppg1/TBG/TBG_LMC/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TBG_LMC.out

# Build rule for target.
TBG_LMC.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TBG_LMC.out
.PHONY : TBG_LMC.out

# fast build rule for target.
TBG_LMC.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TBG_LMC.out.dir/build.make CMakeFiles/TBG_LMC.out.dir/build
.PHONY : TBG_LMC.out/fast

src/Functions.o: src/Functions.cpp.o
.PHONY : src/Functions.o

# target to build an object file
src/Functions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TBG_LMC.out.dir/build.make CMakeFiles/TBG_LMC.out.dir/src/Functions.cpp.o
.PHONY : src/Functions.cpp.o

src/Functions.i: src/Functions.cpp.i
.PHONY : src/Functions.i

# target to preprocess a source file
src/Functions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TBG_LMC.out.dir/build.make CMakeFiles/TBG_LMC.out.dir/src/Functions.cpp.i
.PHONY : src/Functions.cpp.i

src/Functions.s: src/Functions.cpp.s
.PHONY : src/Functions.s

# target to generate assembly for a file
src/Functions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TBG_LMC.out.dir/build.make CMakeFiles/TBG_LMC.out.dir/src/Functions.cpp.s
.PHONY : src/Functions.cpp.s

src/StandardFunctions.o: src/StandardFunctions.cpp.o
.PHONY : src/StandardFunctions.o

# target to build an object file
src/StandardFunctions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TBG_LMC.out.dir/build.make CMakeFiles/TBG_LMC.out.dir/src/StandardFunctions.cpp.o
.PHONY : src/StandardFunctions.cpp.o

src/StandardFunctions.i: src/StandardFunctions.cpp.i
.PHONY : src/StandardFunctions.i

# target to preprocess a source file
src/StandardFunctions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TBG_LMC.out.dir/build.make CMakeFiles/TBG_LMC.out.dir/src/StandardFunctions.cpp.i
.PHONY : src/StandardFunctions.cpp.i

src/StandardFunctions.s: src/StandardFunctions.cpp.s
.PHONY : src/StandardFunctions.s

# target to generate assembly for a file
src/StandardFunctions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TBG_LMC.out.dir/build.make CMakeFiles/TBG_LMC.out.dir/src/StandardFunctions.cpp.s
.PHONY : src/StandardFunctions.cpp.s

src/TBG_LMC.o: src/TBG_LMC.cpp.o
.PHONY : src/TBG_LMC.o

# target to build an object file
src/TBG_LMC.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TBG_LMC.out.dir/build.make CMakeFiles/TBG_LMC.out.dir/src/TBG_LMC.cpp.o
.PHONY : src/TBG_LMC.cpp.o

src/TBG_LMC.i: src/TBG_LMC.cpp.i
.PHONY : src/TBG_LMC.i

# target to preprocess a source file
src/TBG_LMC.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TBG_LMC.out.dir/build.make CMakeFiles/TBG_LMC.out.dir/src/TBG_LMC.cpp.i
.PHONY : src/TBG_LMC.cpp.i

src/TBG_LMC.s: src/TBG_LMC.cpp.s
.PHONY : src/TBG_LMC.s

# target to generate assembly for a file
src/TBG_LMC.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TBG_LMC.out.dir/build.make CMakeFiles/TBG_LMC.out.dir/src/TBG_LMC.cpp.s
.PHONY : src/TBG_LMC.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... TBG_LMC.out"
	@echo "... src/Functions.o"
	@echo "... src/Functions.i"
	@echo "... src/Functions.s"
	@echo "... src/StandardFunctions.o"
	@echo "... src/StandardFunctions.i"
	@echo "... src/StandardFunctions.s"
	@echo "... src/TBG_LMC.o"
	@echo "... src/TBG_LMC.i"
	@echo "... src/TBG_LMC.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

